import pptxgen from "pptxgenjs";
import fs from "fs";
import path from "path";
import { getModel } from "../utils/model.js";
import { uploadToS3 } from "../utils/uploadToS3.js";
import { getDownloadUrl } from "../utils/getDownloadUrl.js";
import { deductCredits } from "../utils/deductCredits.js";
import { checkAgentLimit } from "../config/agentRateLimit.js";

// ─── Design Tokens ────────────────────────────────────────────────────────────

const THEME = {
  dark:    "0F172A",   // cover / conclusion bg
  primary: "2563EB",   // accent color
  white:   "FFFFFF",
  offWhite:"F8FAFC",
  text:    "1E293B",
  muted:   "64748B",
  card:    "EFF6FF",   // light card bg
};

// ─── Helpers ──────────────────────────────────────────────────────────────────

function addCoverSlide(ppt, title, subtitle) {
  const slide = ppt.addSlide();
  slide.background = { color: THEME.dark };

  // large circle decoration (top-right)
  slide.addShape(ppt.ShapeType.ellipse, {
    x: 10.5, y: -1.2, w: 4, h: 4,
    fill: { color: THEME.primary, transparency: 75 },
    line: { color: THEME.primary, transparency: 75 },
  });

  // small circle (bottom-left)
  slide.addShape(ppt.ShapeType.ellipse, {
    x: -0.8, y: 5.5, w: 2.5, h: 2.5,
    fill: { color: THEME.primary, transparency: 80 },
    line: { color: THEME.primary, transparency: 80 },
  });

  // title
  slide.addText(title, {
    x: 0.7, y: 2.0, w: 11.9, h: 1.2,
    fontSize: 36, bold: true, color: THEME.white,
    fontFace: "Calibri", align: "center",
  });

  // subtitle / tagline
  if (subtitle) {
    slide.addText(subtitle, {
      x: 0.7, y: 3.4, w: 11.9, h: 0.5,
      fontSize: 16, color: "94A3B8",
      fontFace: "Calibri", align: "center",
    });
  }

  // footer label
  slide.addText("Generated by CortexAI", {
    x: 0.7, y: 6.7, w: 11.9, h: 0.25,
    fontSize: 10, color: "475569",
    fontFace: "Calibri", align: "center",
  });
}

function addBulletSlide(ppt, slideIndex, title, bullets) {
  const slide = ppt.addSlide();
  slide.background = { color: THEME.white };

  // slide number badge (top-right)
  slide.addShape(ppt.ShapeType.ellipse, {
    x: 12.5, y: 0.15, w: 0.45, h: 0.45,
    fill: { color: THEME.primary },
    line: { color: THEME.primary },
  });
  slide.addText(`${slideIndex}`, {
    x: 12.5, y: 0.15, w: 0.45, h: 0.45,
    fontSize: 10, bold: true, color: THEME.white,
    fontFace: "Calibri", align: "center", valign: "middle",
  });

  // title
  slide.addText(title, {
    x: 0.6, y: 0.25, w: 11.6, h: 0.65,
    fontSize: 28, bold: true, color: THEME.primary,
    fontFace: "Calibri",
  });

  // divider
  slide.addShape(ppt.ShapeType.line, {
    x: 0.6, y: 0.95, w: 11.8, h: 0,
    line: { color: "CBD5E1", width: 1.5 },
  });

  // bullet cards
  const cardH = 0.72;
  const startY = 1.15;
  const gap = 0.12;

  bullets.slice(0, 6).forEach((txt, i) => {
    const y = startY + i * (cardH + gap);

    slide.addShape(ppt.ShapeType.roundRect, {
      x: 0.6, y, w: 11.8, h: cardH,
      fill: { color: i % 2 === 0 ? THEME.card : THEME.offWhite },
      line: { color: "DBEAFE" },
      rectRadius: 0.08,
    });

    // bullet dot
    slide.addShape(ppt.ShapeType.ellipse, {
      x: 0.85, y: y + 0.24, w: 0.22, h: 0.22,
      fill: { color: THEME.primary },
      line: { color: THEME.primary },
    });

    slide.addText(txt, {
      x: 1.2, y: y + 0.1, w: 10.9, h: cardH - 0.2,
      fontSize: 14, color: THEME.text,
      fontFace: "Calibri", valign: "middle",
    });
  });

  // footer
  slide.addText("CortexAI", {
    x: 0.6, y: 7.0, w: 2, h: 0.2,
    fontSize: 9, color: THEME.muted, fontFace: "Calibri",
  });
}

function addStatSlide(ppt, slideIndex, title, stats) {
  // stats = [{label, value}, ...]  — used for key-metrics style slides
  const slide = ppt.addSlide();
  slide.background = { color: THEME.dark };

  slide.addText(title, {
    x: 0.6, y: 0.3, w: 12, h: 0.65,
    fontSize: 28, bold: true, color: THEME.white,
    fontFace: "Calibri",
  });
  slide.addShape(ppt.ShapeType.line, {
    x: 0.6, y: 1.0, w: 11.8, h: 0,
    line: { color: THEME.primary, width: 2 },
  });

  const cols = stats.length <= 3 ? stats.length : 4;
  const cardW = 11.8 / cols;
  const startX = 0.6;

  stats.slice(0, 4).forEach((s, i) => {
    const x = startX + i * cardW;
    slide.addShape(ppt.ShapeType.roundRect, {
      x: x + 0.1, y: 1.5, w: cardW - 0.2, h: 3.8,
      fill: { color: "1E3A5F" },
      line: { color: THEME.primary, width: 1 },
      rectRadius: 0.12,
    });
    slide.addText(s.value, {
      x: x + 0.1, y: 1.9, w: cardW - 0.2, h: 1.5,
      fontSize: 40, bold: true, color: THEME.primary,
      fontFace: "Calibri", align: "center",
    });
    slide.addText(s.label, {
      x: x + 0.1, y: 3.5, w: cardW - 0.2, h: 1.4,
      fontSize: 14, color: "CBD5E1",
      fontFace: "Calibri", align: "center",
    });
  });

  slide.addText("CortexAI", {
    x: 0.6, y: 7.0, w: 2, h: 0.2,
    fontSize: 9, color: THEME.muted, fontFace: "Calibri",
  });
}

function addConclusionSlide(ppt, title, points) {
  const slide = ppt.addSlide();
  slide.background = { color: THEME.primary };

  // decorative circle
  slide.addShape(ppt.ShapeType.ellipse, {
    x: 10, y: 4.5, w: 5, h: 5,
    fill: { color: "1D4ED8", transparency: 60 },
    line: { color: "1D4ED8", transparency: 60 },
  });

  slide.addText(title, {
    x: 0.7, y: 1.0, w: 9, h: 0.9,
    fontSize: 34, bold: true, color: THEME.white,
    fontFace: "Calibri",
  });
  slide.addText("Key Takeaways", {
    x: 0.7, y: 2.1, w: 9, h: 0.4,
    fontSize: 14, color: "BFDBFE",
    fontFace: "Calibri",
  });

  points.slice(0, 4).forEach((p, i) => {
    slide.addShape(ppt.ShapeType.ellipse, {
      x: 0.7, y: 2.7 + i * 0.75, w: 0.3, h: 0.3,
      fill: { color: THEME.white },
      line: { color: THEME.white },
    });
    slide.addText(p, {
      x: 1.2, y: 2.65 + i * 0.75, w: 8.5, h: 0.55,
      fontSize: 15, color: THEME.white,
      fontFace: "Calibri",
    });
  });

  slide.addText("Generated by CortexAI", {
    x: 0.7, y: 7.0, w: 11.9, h: 0.2,
    fontSize: 9, color: "BFDBFE",
    fontFace: "Calibri", align: "center",
  });
}

// ─── Parse AI Response ────────────────────────────────────────────────────────

function parseResponse(content) {
  const result = {
    title: "",
    subtitle: "",
    slides: [],
  };

  const titleMatch = content.match(/^TITLE:\s*(.+)/m);
  result.title = titleMatch?.[1]?.trim() || "Presentation";

  const subtitleMatch = content.match(/^SUBTITLE:\s*(.+)/m);
  result.subtitle = subtitleMatch?.[1]?.trim() || "";

  const rawSlides = content.split(/^SLIDE:/m).slice(1);

  rawSlides.forEach((raw) => {
    const lines = raw.split("\n").map(l => l.trim()).filter(Boolean);
    const titleLine = lines.find(l => l.startsWith("Title:"));
    const typeLine  = lines.find(l => l.startsWith("Type:"));

    const title = titleLine?.replace("Title:", "").trim() || "Slide";
    const type  = typeLine?.replace("Type:", "").trim().toLowerCase() || "bullets";

    const items = lines
      .filter(l => l.startsWith("- "))
      .map(l => l.replace(/^-\s*/, "").trim());

    // For STATS slides: "Label | Value"
    const stats = items.map(i => {
      const parts = i.split("|").map(p => p.trim());
      return parts.length === 2
        ? { label: parts[0], value: parts[1] }
        : { label: i, value: "" };
    });

    result.slides.push({ title, type, items, stats });
  });

  return result;
}

// ─── Agent ────────────────────────────────────────────────────────────────────

export const pptAgent = async (state) => {
  try {

    await checkAgentLimit(
        state.userId,
        "ppt"
      );

      await deductCredits(

        state.userId,

        "ppt"

    ); 
    const llm = getModel("ppt");

    const aiResponse = await llm.invoke(`
Create a professional PowerPoint presentation on the topic below.

Topic: ${state.prompt}

Output Rules:
- No markdown, no explanation, only the format below.
- Generate exactly 8 slides after the title.
- Slide types: bullets | stats | conclusion
  - bullets: 4-6 bullet points (most slides)
  - stats: 3-4 key metrics as "Label | Value" (use once for impact)
  - conclusion: 3-4 short takeaway points (last slide)

Format:

TITLE: Presentation Title
SUBTITLE: One-line tagline or description

SLIDE:
Type: bullets
Title: Introduction
- Point one
- Point two
- Point three
- Point four

SLIDE:
Type: stats
Title: Key Numbers
- Users Reached | 10M+
- Revenue Growth | 42%
- Countries | 30+

SLIDE:
Type: conclusion
Title: Conclusion
- Key takeaway one
- Key takeaway two
- Key takeaway three
`);

    const content = aiResponse.content.trim();
    const parsed  = parseResponse(content);

    const ppt = new pptxgen();
    ppt.layout  = "LAYOUT_WIDE";
    ppt.author  = "CortexAI";
    ppt.subject = state.prompt;
    ppt.title   = parsed.title;

    // Cover
    addCoverSlide(ppt, parsed.title, parsed.subtitle);

    // Content slides
    parsed.slides.forEach((slide, i) => {
      const num = i + 1;
      if (slide.type === "stats") {
        addStatSlide(ppt, num, slide.title, slide.stats);
      } else if (slide.type === "conclusion") {
        addConclusionSlide(ppt, slide.title, slide.items);
      } else {
        addBulletSlide(ppt, num, slide.title, slide.items);
      }
    });

    // Save
   const fileName =
  `ppt-${Date.now()}.pptx`;

const buffer =
  await ppt.write({
    outputType: "nodebuffer"
  });

await uploadToS3(
  buffer,
  fileName,
  "application/vnd.openxmlformats-officedocument.presentationml.presentation"
);

const downloadUrl =
  await getDownloadUrl(
    fileName,
    24*60*60
  );

    return {
  ...state,

  response: `
# ✅ Presentation Generated Successfully

📊 **${parsed.title}**

📥 [Download PPT](${downloadUrl})

⏳ Link expires in 10 minutes.
`
};
  } catch (error) {
    console.log("PPT Agent Error:", error);
    return { ...state, response: "Failed to generate presentation." };
  }
};